### PR TITLE
Added Spotify API Token auto generation

### PR DESCRIPTION
**Pull request by BRAVO68WEB**
Added Spotify API Token will be automatically generated and created proper Config.json file

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
@b3h3m0th Did you checked my Code??

**Comment by b3h3m0th** [comment]
Hey nice stuff man! LGTM

**Comment by b3h3m0th** [comment]
How come you commit to Britta. Just interested :D

**Comment by BRAVO68WEB** [comment]
I just like your project so I would like to actively contributed

I will like to add new features

Awesome work by the way 👍🏼

**Comment by BRAVO68WEB** [comment]
@b3h3m0th Lets Grew this bot together !!

**Comment by b3h3m0th** [comment]
Nice! yeah gonna be awesome! Thanks for doing the Spotify thingy 🥇

**Comment by b3h3m0th** [comment]
Hey i just tried out your code and it's working just perfectly! I can't describe how glad I am :D 
I've been trying doing this for sooo long. Thanks so much!

**Comment by BRAVO68WEB** [comment]
No worries lets make it large,
Can you give me contributor role so that i can directly open pull request. I wont merge with out your permission.

**Comment by b3h3m0th** [comment]
Oh yes sure.

**Comment by BRAVO68WEB** [comment]
Thank you

**Pull request merged**
